name = "erlang_example"
version = "0.1.0"
description = "Squall Erlang example - Rick and Morty GraphQL API"

[dependencies]
gleam_stdlib = ">= 0.65.0 and < 0.66.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
squall = { path = "../.." }
